### ISSUE TITLE
ExtDist package is on CRAN archive only

### ISSUE THREAD

**Issue by ginolhac** [andrewcparnell/bhm_course#1]
Hi,

I will be following your course shortly, and looking at the [prerequisites](https://github.com/andrewcparnell/bhm_course/blob/master/Prerequisites.Rmd), `ExtDist` is not available on [CRAN](https://cran.r-project.org/web/packages/ExtDist/index.html). Only the archive. Should we install an archived version? Last available version is **0.6-3** (May 2015).

Best,

**Comment by andrewcparnell** [comment]
Thanks for pointing out. Updated now with a new package.

Andrew

**Comment by ginolhac** [comment]
Thanks!
